### ISSUE TITLE
Possible optimisations

### ISSUE THREAD

**Issue by dpgeorge** [peterhinch/micropython-epaper#1]
Here are some possible optimisations for the driver (epd.py):
1. _SPI_send is called with a tuple of ints, and then the function itself converts the tuple to a bytes object before sending the data over the bus.  Currently in uPy a tuple is created _each time_ it is used in the code, even if it's a constant tuple.  This will be optimised away one day, but at the moment that's how it is.  So every call to _SPI_send is creating a tuple, then creating a bytes object from this tuple.  It would be much more efficient in time and RAM to give _SPI_send a bytes object to begin with.  Eg: `_SPI_send(b'\x70\x02')`.  You don't really lose readability/writability because you can still write hex numbers.  And in fact the code is shorter to write!  With this approach no heap RAM needs to be allocated.
2. In _line_fixed and _line, when calling spi_send_byte, you could use a bytes object to send multiple bytes at once.  Eg: `spi_send_byte(b'\x72\x00')`.
3. Viper pointers can be used to greatly speed up _setbuf_fixed and _setbuf_data.  Eg:

``` python
buf = ptr8(self.linebuf)
image = ptr8(self.image)
```

This tells viper that these variables are pointers to 8-bit data (bytes).  Loads and stores to these variables will be direct machine code rather than a call to the Python runtime function subscr.

**Comment by peterhinch** [comment]
Now implemented with impressive results. Thank you!
