### ISSUE TITLE
Two Errors

### ISSUE THREAD

**Issue by capaulson** [peterhinch/micropython-epaper#2]
I have two errors that I can't crack. The first is on loading the module:

```
>>> import epaper
ViperTypeError: can't do binary op between types -1 and 2
ERROR: stack size not back to zero; got 1
ViperTypeError: can't do binary op between types -1 and 2
ERROR: stack size not back to zero; got 1
ViperTypeError: can't do binary op between types -1 and 2
ERROR: stack size not back to zero; got 1
```

This doesn't seem to impact too much, but the display doesn't write, so perhaps I'm wrong. The next issue encountered is on writing. I get TypeError: function does not take keyword arguments on writing. The issues seem to come from:

`self._line_fixed(line, 0, set_voltage_limit = True)`

I get: 

`TypeError: function does not take keyword arguments`

The function def looks like: 

```
    @micropython.native
    def _line_fixed(self, line, fixed_value, set_voltage_limit=False):
```

So I don't see the issue. Any ideas?

Thanks for publishing this library.

**Comment by peterhinch** [comment]
That is puzzling. What version of Pyboard firmware are you running? I suggest upgrading to the latest build. I'll do likewise and we can compare notes.

As the errors centre around my use of the native and viper emitters it is easy to remove the decorators. Removing native decorators is simply a matter of commenting them out: this might be worth doing to see if the second error goes away. Removing viper decorators needs a little more work: in the declarations you'll need to remove the type hints and in function bodies the ptr8 casts, e.g.

``` python
    def _setbuf_fixed(self, line, fixed_value):
        index = 0                           # odd pixels
        buf = self.linebuf #ptr8 removed
```

Removing the decorators will inevitably make updates slower. The viper optimised sections in  particular have had a considerable amount of testing and I'm puzzled that you're seeing this fault. If it isn't a firmware issue I might need to request some guidance from Damien.

**Comment by peterhinch** [comment]
I've now updated to today's build (named below): the test script from the README runs without error. Please let me know if your experience is similar or not:

``` python
Entering REPL. Use Control-X to exit.

Micro Python v1.4.5-74-g75a811a on 2015-09-08; PYBv1.0 with STM32F405RG
Type "help()" for more information.
>>> 
>>> import epaper
>>> a = epaper.Display('Y')
>>> a.rect(20, 20, 150, 150, 3)
>>> a.show()
>>> 
```

Incidentally, just to ensure we're singing from the same hymn sheet, please could you ensure you have the latest version of my driver. While the code you're having trouble with hasn't changed recently it's still best if we're running the same build of driver on identical hardware and firmware.

**Comment by capaulson** [comment]
Hi Peter, 
I concur. This was my fault. I had one pyboard flashed with the github version and one not updated. I was testing with the later. You code works great. Thanks for making your micropython code public, I've found all of it very useful. Best, Chris
